lessons:
  outputs:
    dev:
      dataset: dbt_JCav23
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dbt-udemy-447710
      threads: 60
      type: bigquery
  target: dev